language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer config http-basic.repo.magento.com $MAGENTO_REPO_PUBLIC_KEY $MAGENTO_REPO_PRIVATE_KEY

install:
    - composer install --prefer-source --no-interaction --dev

script: php ./vendor/bin/phpunit
